export const EXERCISE_DATABASE =
[
 "Bench Press",
  "Incline Bench Press",
  "Decline Bench Press",
  "Dumbbell Bench Press",
  "Incline Dumbbell Press",
  "Chest Fly",
  "Cable Fly",
  "Pec Deck",
  "Push Up",
  "Wide Push Up",
  "Decline Push Up",
  "Dips (Chest)",
  "Machine Chest Press",
  "Svend Press",

  "Deadlift",
  "Romanian Deadlift",
  "Rack Pull",
  "Lat Pulldown",
  "Pull Up",
  "Chin Up",
  "Seated Cable Row",
  "Barbell Row",
  "Dumbbell Row",
  "T-Bar Row",
  "Face Pull",
  "Straight Arm Pulldown",
  "Machine Row",
  "Meadows Row",
  "Inverted Row",

  "Overhead Press",
  "Military Press",
  "Arnold Press",
  "Lateral Raise",
  "Front Raise",
  "Rear Delt Fly",
  "Upright Row",
  "Cable Lateral Raise",
  "Machine Shoulder Press",
  "Shrugs",

  "Barbell Curl",
  "Dumbbell Curl",
  "Hammer Curl",
  "Preacher Curl",
  "Concentration Curl",
  "Cable Curl",
  "Incline Curl",
  "Zottman Curl",
  "Spider Curl",

  "Close Grip Bench Press",
  "Triceps Pushdown",
  "Overhead Triceps Extension",
  "Skull Crusher",
  "Dips",
  "Kickback",
  "Rope Pushdown",
  "JM Press",
  "Bench Dip",

  "Squat",
  "Front Squat",
  "Goblet Squat",
  "Hack Squat",
  "Leg Press",
  "Lunges",
  "Walking Lunges",
  "Bulgarian Split Squat",
  "Leg Extension",
  "Leg Curl",
  "Seated Leg Curl",
  "Standing Calf Raise",
  "Seated Calf Raise",
  "Hip Thrust",
  "Glute Bridge",
  "Step Up",
  "Sissy Squat",

  "Plank",
  "Side Plank",
  "Crunch",
  "Sit Up",
  "Hanging Leg Raise",
  "Ab Wheel Rollout",
  "Russian Twist",
  "Cable Crunch",
  "Mountain Climber",
  "Bicycle Crunch",
  "Flutter Kicks",

  "Treadmill Run",
  "Cycling",
  "Rowing Machine",
  "Jump Rope",
  "Stair Climber",
  "Elliptical",
  "HIIT",
  "Sprints",
  "Shadow Boxing",

  "Kettlebell Swing",
  "Farmer Walk",
  "Battle Rope",
  "Box Jump",
  "Wall Ball",
  "Sled Push",
  "Bear Crawl",
  "Turkish Get Up",
  "Medicine Ball Slam",

  "Clean",
  "Clean and Jerk",
  "Snatch",
  "Power Clean",
  "Push Press",
  "Split Jerk",
  "Hang Clean",
  "Hang Snatch",

  "Muscle Up",
  "Handstand Push Up",
  "Pistol Squat",
  "L-Sit",
  "Planche",
  "Front Lever",
  "Back Lever"

];

